### ISSUE TITLE
Expansion of events fails when expanding event starts exactly at max_datetime

### ISSUE THREAD

**Issue by Jorricks** [Jorricks/ical-reader#9]
Error;

```
Traceback (most recent call last):
  File "/home/bigdata/venv/lib64/python3.9/site-packages/duty_board/worker_loop.py", line 112, in update_all_outdated_calendars
    calendar = plugin.sync_calendar(calendar=calendar, session=session)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/duty_board/plugin/ical_plugin_mixin.py", line 88, in sync_calendar
    for event in self._get_events_for_upcoming_month(calendar.icalendar_url, calendar.event_prefix or ""):
  File "/home/bigdata/venv/lib64/python3.9/site-packages/duty_board/plugin/ical_plugin_mixin.py", line 39, in _get_events_for_upcoming_month
    return [
  File "/home/bigdata/venv/lib64/python3.9/site-packages/duty_board/plugin/ical_plugin_mixin.py", line 39, in <listcomp>
    return [
  File "/home/bigdata/venv/lib64/python3.9/site-packages/ical_library/timeline.py", line 136, in overlapping
    for timespan, event in self.iterate():
  File "/home/bigdata/venv/lib64/python3.9/site-packages/ical_library/timeline.py", line 120, in iterate
    heap: List[TimespanWithParent] = self.__explode_recurring_components()
  File "/home/bigdata/venv/lib64/python3.9/site-packages/ical_library/timeline.py", line 101, in __explode_recurring_components
    list_of_timestamps_with_parents.extend(
  File "/home/bigdata/venv/lib64/python3.9/site-packages/ical_library/ical_components/v_event.py", line 216, in expand_component_in_range
    for event_start_time, event_end_time in iterator:
  File "/home/bigdata/venv/lib64/python3.9/site-packages/ical_library/help_modules/property_utils.py", line 252, in expand_component_in_range
    for rrule_time in iterator:
  File "/home/bigdata/venv/lib64/python3.9/site-packages/ical_library/help_modules/property_utils.py", line 129, in _yield_rrule_list
    for rrule_time in iterator:
  File "/home/bigdata/venv/lib64/python3.9/site-packages/ical_library/ical_properties/rrule.py", line 275, in sequence_iterator
    raise ValueError(f"This should not be the case: {starting_datetime=} >= {max_datetime=} .")
ValueError: This should not be the case: starting_datetime=Date(2023, 3, 8) >= max_datetime=Date(2023, 3, 8) .
```

Corresponding VEvent:
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20230308
DTEND;VALUE=DATE:20230315
DTSTAMP:20230208T071445Z
UID:abc@google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=abc@gmail.com;X-NUM-GUESTS=0:mailto:abc@gmail.com
RECURRENCE-ID;VALUE=DATE:20230308
CREATED:20220223T123118Z
DESCRIPTION:
LAST-MODIFIED:20230118T224003Z
LOCATION:
SEQUENCE:3
STATUS:CONFIRMED
SUMMARY:Data Duty 24/7:  @abc
TRANSP:TRANSPARENT
END:VEVENT
BEGIN:VEVENT
DTSTART;VALUE=DATE:20230308
DTEND;VALUE=DATE:20230315
RRULE:FREQ=WEEKLY;WKST=MO;COUNT=4;INTERVAL=12;BYDAY=WE
DTSTAMP:20230208T071445Z
UID:abc@google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=abc@gmail.com;X-NUM-GUESTS=0:mailto:abc@gmail.com
CREATED:20220223T123118Z
DESCRIPTION:
LAST-MODIFIED:20230118T224003Z
LOCATION:
SEQUENCE:3
STATUS:CONFIRMED
SUMMARY:Data Duty 24/7:  @abc
TRANSP:TRANSPARENT
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
BEGIN:VALARM
ACTION:AUDIO
TRIGGER:-PT15H
X-WR-ALARMUID:9C6E4D2C-0153-4CE9-8121-FCB2933FF375
UID:9C6E4D2C-0153-4CE9-8121-FCB2933FF375
ATTACH;VALUE=URI:Chord
X-APPLE-DEFAULT-ALARM:TRUE
ACKNOWLEDGED:20221011T075815Z
END:VALARM
END:VEVENT
```

**Comment by Jorricks** [comment]
Fixed in https://github.com/Jorricks/iCal-library/releases/tag/0.2.2
